### ISSUE TITLE
error when running virtualenv2 venv

### ISSUE THREAD

**Issue by afiqqo231** [akhilnarang/scripts#118]
Hi. Can you help me? When i run the command virtualenv2 venv I get error.

"Traceback (most recent call last):
  File "/usr/bin/virtualenv2", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'distlib<1,>=0.3.0' distribution was not found and is required by virtualenv"
can you help me? Thank you

**Comment by RealAkito** [comment]
Distlib is not installed. You can do it via `python -m pip install distlib`

You must have pip installed in this case.

**Comment by josevega96** [comment]
just solved that you need the pyhton2-distlib package 

`sudo pacman -S python2-distlib`

**Comment by RealAkito** [comment]
> just solved that you need the pyhton2-distlib package
> 
> `sudo pacman -S python2-distlib`

@akhilnarang this should be added to Arch Linux setup script.
