### ISSUE TITLE
need support deepin ?

### ISSUE THREAD

**Issue by aohanhongzhi** [akhilnarang/scripts#180]
https://www.deepin.org/
`
Executing: /tmp/apt-key-gpghome.OBuHUu74oo/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com --recv-key C99B11DEB97541F0
gpg: key C99B11DEB97541F0: public key "Nate Smith <vilmibm@github.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Deepin/apricot

`

**Comment by akhilnarang** [comment]
I haven't used Deepin, so not sure what's wrong.
If you can fix it, please do submit a PR with the changes to support Deepin properly.
